spring:
    jpa:
      database: MYSQL
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/vue
      username: ouyang
      password: oyh1203oy
      driver-class-name: com.mysql.jdbc.Driver